#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

# --

diff <(trl -W @ -S ' ' one two three) - <<'EOF' || die "single-char wrapper string, single-line: unexpected output"
@one two three@
EOF

diff <(trl -W '[  ]' -S ' ' one two three) - <<'EOF' || die "multi-char wrapper string, single-line: unexpected output"
[ one two three ]
EOF

# --

diff <(trl -W @ 'one two three') - <<'EOF' || die "single-char wrapper string, multi-line: unexpected output"
@
one
two
three
@
EOF

diff <(trl -W '[]' 'one two three') - <<'EOF' || die "multi-char wrapper string, multi-line: unexpected output"
[
one
two
three
]
EOF
